tabWidth: 4
printWidth: 90
overrides:
  - files: "*.json"
    options:
      printWidth: 0
  - files: "*.yml"
    options:
      tabWidth: 2
plugins:
  - "@ianvs/prettier-plugin-sort-imports"
  - "prettier-plugin-jsdoc"
  - "prettier-plugin-pkg"
jsdocSeparateReturnsFromParam: true
tsdoc: true
importOrder:
  - "<BUILTIN_MODULES>"
  - "<TYPES>^node:"
  - ""
  - "<THIRD_PARTY_MODULES>"
  - "<TYPES>"
  - ""
  - "^@adonaix/"
  - "<TYPES>^@adonaix/"
  - ""
  - "^~/"
  - "<TYPES>^~/"
  - ""
  - "^\\."
  - "<TYPES>^\\."
